version: "3.8"

services:
  postgress:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL: postgresql://neondb_owner:npg_d1HkpRWLyE8g@ep-curly-haze-a4a5gg3s-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
    depends_on:
      - postgres

volumes:
  postgres_data:
